from setuptools import setup, find_packages

setup(
    name="recontext",
    version="1.0.0",
    description="3D Scene Reconstruction with Semantic Understanding",
    author="RECONTEXT Team",
    author_email="info@recontext.ai",
    url="https://github.com/your-org/recontext",
    packages=find_packages(),
    install_requires=[
        "numpy>=1.19.0",
        "torch>=1.10.0",
        "torchvision>=0.11.0",
        "opencv-python>=4.5.0",
        "open3d>=0.13.0",
        "networkx>=2.6.0",
        "scipy>=1.7.0",
        "matplotlib>=3.4.0",
        "tqdm>=4.60.0",
        "pyyaml>=5.4.0",
        "pillow>=8.2.0",
        "scikit-image>=0.18.0",
        "pyqt5>=5.15.0",
        "transformers>=4.10.0",
    ],
    extras_require={
        "dev": [
            "pytest>=6.2.0",
            "flake8>=3.9.0",
            "black>=21.5b0",
            "isort>=5.9.0",
            "mypy>=0.812",
        ],
        "docs": [
            "sphinx>=4.0.0",
            "sphinx-rtd-theme>=0.5.0",
            "nbsphinx>=0.8.0",
        ],
    },
    classifiers=[
        "Development Status :: 4 - Beta",
        "Intended Audience :: Science/Research",
        "Topic :: Scientific/Engineering :: Artificial Intelligence",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
    ],
    python_requires=">=3.8",
)